
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aadesh
 */
public class UnitJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UnitJFrame
     */
    public UnitJFrame() {
        initComponents();jLabelnote.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldQuant = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelunit = new javax.swing.JLabel();
        jLabelnote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conversion Calculator");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the quantity :");

        TextFieldQuant.setText("0");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose the category");

        jComboBox2.addItem("Currency");
        jComboBox2.addItem("length");
        jComboBox2.addItem("weight");
        jComboBox2.addItem("area");
        jComboBox2.addItem("volume");
        jComboBox2.addItem("temprature");
        jComboBox2.addItem("pressure");
        jComboBox2.addItem("time");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelunit.setBackground(new java.awt.Color(0, 0, 0));
        jLabelunit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelunit.setForeground(new java.awt.Color(255, 255, 255));

        jLabelnote.setBackground(new java.awt.Color(0, 0, 0));
        jLabelnote.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnote.setText("NOTE: Please reset to choose another category.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabelunit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelunit)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        jComboBox2.addActionListener(jComboBox2);
        
        Object selected=jComboBox2.getSelectedItem();
        
        
       if(selected.equals("length")){
           jComboBox1.removeAllItems();
           jComboBox1.addItem("mm");
           jComboBox1.addItem("cm");
           jComboBox1.addItem("m");
           jComboBox1.addItem("km");
           jComboBox1.addItem("inch");
           jComboBox1.addItem("foot");
           jComboBox2.setVisible(false);
           jLabelunit.setText("length conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("Currency")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("INR");
           jComboBox1.addItem("USD");
           jComboBox1.addItem("EURO");
           jComboBox1.addItem("YEN");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Currency conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("weight")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("mg");
           jComboBox1.addItem("g");
           jComboBox1.addItem("kg");
           jComboBox2.setVisible(false);
           jLabelunit.setText("weight conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("temprature")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("K");
           jComboBox1.addItem("deg C");
           jComboBox1.addItem("deg F");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Temprature conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("area")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("sq mm");
           jComboBox1.addItem("sq cm");
           jComboBox1.addItem("sq m");
           jComboBox1.addItem("sq foot");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Area conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("volume")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("ml");
           jComboBox1.addItem("cubic cm");
           jComboBox1.addItem("l");
           jComboBox1.addItem("cubic m");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Volume conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("pressure")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("atm");
           jComboBox1.addItem("pascal");
           jComboBox1.addItem("mmHg");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Pressure conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
        }
        else if(selected.equals("time")){
            jComboBox1.removeAllItems();
           jComboBox1.addItem("ms");
           jComboBox1.addItem("sec");
           jComboBox1.addItem("min");
           jComboBox1.addItem("hrs");
           jComboBox2.setVisible(false);
           jLabelunit.setText("Time conversion");
           jLabel3.setVisible(false);
           jLabelunit.setVisible(true);
           jLabelnote.setVisible(true);
           
        }// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1.addActionListener(jComboBox1);
        Object selected=jComboBox1.getSelectedItem();
        
        double a=Double.parseDouble(TextFieldQuant.getText());
        if(selected.equals("K"))
            jTextArea1.setText("\n"+a+" K\n"+(a-273.15)+" deg C\n"+((a-273.15)*9/5+32)+" deg F");
        else if(selected.equals("deg C"))
            jTextArea1.setText("\n"+(a+273.15)+" K\n"+(a)+" deg C\n"+((a*9/5)+32)+" deg F");
        else if(selected.equals("deg F"))
            jTextArea1.setText("\n"+(a+254.92)+" K\n"+((a-32)*5/9)+" deg C\n"+(a)+" deg F");
        else if(selected.equals("INR"))
            jTextArea1.setText("\n"+a+" INR\n"+(a/68.34)+" USD\n"+(a/79.72)+" EURO\n"+(a*1.63)+" YEN\n");
        else if(selected.equals("USD"))
            jTextArea1.setText("\n"+(a*68.34)+" INR\n"+(a)+" USD\n"+(68.34*a/79.72)+" EURO\n"+(a*1.63*68.34)+" YEN\n");
        else if(selected.equals("EURO"))
            jTextArea1.setText("\n"+(a*79.72)+" INR\n"+(79.72*a/68.34)+" USD\n"+(a)+" EURO\n"+(a*1.63*79.72)+" YEN\n");
        else if(selected.equals("INR"))
            jTextArea1.setText("\n"+(a/1.63)+" INR\n"+(a/(1.63*68.34))+" USD\n"+(a/(1.63*79.72))+" EURO\n"+(a)+" YEN\n");
    // TODO add your handling code here:
        else if(selected.equals("ms"))
        jTextArea1.setText("\n"+a+" ms\n"+(a/100)+" sec\n"+(a/6000)+" min\n"+(a/360000)+" hrs");
        else if(selected.equals("sec"))
        jTextArea1.setText("\n"+a*100+" ms\n"+(a)+" sec\n"+(a/60)+" min\n"+(a/3600)+" hrs");
        else if(selected.equals("min"))
        jTextArea1.setText("\n"+(a*6000)+" ms\n"+(a*60)+" sec\n"+(a)+" min\n"+(a/60)+" hrs");
        else if(selected.equals("hrs"))
        jTextArea1.setText("\n"+(a*360000)+" ms\n"+(a*3600)+" sec\n"+(a*60)+" min\n"+(a)+" hrs");
        else if(selected.equals("mg"))
        jTextArea1.setText("\n"+a+" mg\n"+(a*.001)+" g\n"+(a*.000001)+" kg");
        else if(selected.equals("g"))
        jTextArea1.setText("\n"+(a*1000)+" mg\n"+(a)+" g\n"+(a/1000)+" kg");
        else if(selected.equals("kg"))
        jTextArea1.setText("\n"+(a*1000000)+" mg\n"+(a*1000)+" g\n"+(a)+" kg");
        else if(selected.equals("atm"))
        jTextArea1.setText("\n"+a+" atm\n"+(a*101325)+" pascal\n"+(a*760.0021)+" mmHg");
        else if(selected.equals("pascal"))
        jTextArea1.setText("\n"+(a/101325)+" atm\n"+(a)+" pascal\n"+(a*0.00750064)+" mmHg");
        else if(selected.equals("mmHg"))
        jTextArea1.setText("\n"+(a*.00131579)+" atm\n"+(a*133.322)+" pascal\n"+(a)+" mmHg");
        else if(selected.equals("mm"))
        jTextArea1.setText("\n"+a+" mm\n"+(a*.1)+" cm\n"+(a*.001)+" m\n"+(a*.000001)+" km\n"+(a*.00328084)+" foot\n");
        else if(selected.equals("cm"))
        jTextArea1.setText("\n"+(a*10)+" mm\n"+(a)+" cm\n"+(a*.01)+" m\n"+(a*.00001)+" km\n"+(a*.0328084)+" foot\n");
        else if(selected.equals("m"))
        jTextArea1.setText("\n"+(a*1000)+" mm\n"+(a*100)+" cm\n"+(a)+" m\n"+(a*.001)+" km\n"+(a*3.28084)+" foot\n");
        else if(selected.equals("km"))
        jTextArea1.setText("\n"+(a*1000000)+" mm\n"+(a*100000)+" cm\n"+(a*1000)+" m\n"+(a)+" km\n"+(a*3280.84)+" foot\n");
        else if(selected.equals("foot"))
        jTextArea1.setText("\n"+(a*304.8)+" mm\n"+(a*30.48)+" cm\n"+(a*.3048)+" m\n"+(a*.0003048)+" km\n"+(a)+" foot\n");
        else if(selected.equals("sq mm"))
        jTextArea1.setText("\n"+(a)+" sq mm\n"+(a*.01)+" sq cm\n"+(a*.000001)+" sq m\n"+(a*.000000000001)+" sq km\n"+(a*.0000107639)+" sq foot\n");
        else if(selected.equals("sq cm"))
        jTextArea1.setText("\n"+(a*100)+" sq mm\n"+(a)+" sq cm\n"+(a*.0001)+" sq m\n"+(a*.0000000001)+" sq km\n"+(a*.00107639)+" sq foot\n");
        else if(selected.equals("sq m"))
        jTextArea1.setText("\n"+(a*1000000)+" sq mm\n"+(a*10000)+" sq cm\n"+(a)+" sq m\n"+(a*.000001)+" sq km\n"+(a*10.7639)+" sq foot\n");
        else if(selected.equals("sq foot"))
        jTextArea1.setText("\n"+(a*92903.04)+" sq mm\n"+(a*929.0304)+" sq cm\n"+(a*.09290304)+" sq m\n"+(a)+" sq foot\n");
        else if(selected.equals("ml"))
        jTextArea1.setText("\n"+(a)+" ml\n"+(a*1)+" cubic cm\n"+(a*.001)+" liters\n"+(a*.000001)+" cubic meters\n");
        else if(selected.equals("cubic cm"))
        jTextArea1.setText("\n"+(a)+" ml\n"+(a*1)+" cubic cm\n"+(a*.001)+" liters\n"+(a*.000001)+" cubic meters\n");
        else if(selected.equals("l"))
        jTextArea1.setText("\n"+(a*1000)+" ml\n"+(a*1000)+" cubic cm\n"+(a)+" liters\n"+(a*.001)+" cubic meters\n");
        else if(selected.equals("cubic m"))
        jTextArea1.setText("\n"+(a*1000000)+" ml\n"+(a*1000000)+" cubic cm\n"+(a*1000)+" liters\n"+(a)+" cubic meters\n");
        
        
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     System.exit(0);
     this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    UnitJFrame j=new UnitJFrame();
    this.dispose();
    j.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldQuant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelnote;
    private javax.swing.JLabel jLabelunit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
